branches:
  only:
  - master
language: python
cache: yarn
python:
  - "3.5"
# command to install dependencies
install:
  - pip install fandogh-cli --upgrade
  - pip install docker
  
  # command to run tests
script:
  - echo $TRAVIS_COMMIT
  - docker login --username=hesam80 --password=sa13801380
  - docker build -t bestoon:latset .
  # docker run -d -p 8000:8000 bestoon:latest
 
